apiVersion: v1
kind: Service
metadata:
  name: node-k8s-service
spec:
  type: NodePort
  selector:
    app: node-k8s-app
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 31000
